// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_jtK-MKjp9rn6QCFOds0uuZG8LTGEI6E',
    appId: '1:704390352916:web:9bbea00161cfe9465b5701',
    messagingSenderId: '704390352916',
    projectId: 'grocery-ease-db924',
    authDomain: 'grocery-ease-db924.firebaseapp.com',
    storageBucket: 'grocery-ease-db924.appspot.com',
    measurementId: 'G-XMQLP1BNXZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBfZeMGUvPejAc8j-be0VhJC9766s2fgo',
    appId: '1:704390352916:android:fea08899fa2159a65b5701',
    messagingSenderId: '704390352916',
    projectId: 'grocery-ease-db924',
    storageBucket: 'grocery-ease-db924.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPKdgArg0md5miUvyUZJDfmdVIXmzIRsM',
    appId: '1:704390352916:ios:77612841e61f94bb5b5701',
    messagingSenderId: '704390352916',
    projectId: 'grocery-ease-db924',
    storageBucket: 'grocery-ease-db924.appspot.com',
    iosBundleId: 'com.example.groceryAppAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPKdgArg0md5miUvyUZJDfmdVIXmzIRsM',
    appId: '1:704390352916:ios:77612841e61f94bb5b5701',
    messagingSenderId: '704390352916',
    projectId: 'grocery-ease-db924',
    storageBucket: 'grocery-ease-db924.appspot.com',
    iosBundleId: 'com.example.groceryAppAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_jtK-MKjp9rn6QCFOds0uuZG8LTGEI6E',
    appId: '1:704390352916:web:6dd6084c50d5e22b5b5701',
    messagingSenderId: '704390352916',
    projectId: 'grocery-ease-db924',
    authDomain: 'grocery-ease-db924.firebaseapp.com',
    storageBucket: 'grocery-ease-db924.appspot.com',
    measurementId: 'G-TSDKC12QN2',
  );
}
